### ISSUE TITLE
rating & count & remove helpful

### ISSUE THREAD

**Issue by ravi-aratchige** [sasankaweera123/Web_Scraping_Project_0001#1]
Add rating code and count code
And remove helpful because it doesn't come with source code

`count = soup.find('div', id='reviewContentSection').find('div',id='reviewsSection').find('div',class_='review-section-header').h2.text`

`rating = review_section_left.find('div', class_='ebay-star-rating').meta['content']`

**Comment by sasankaweera123** [comment]
This was ver helpful, Thank you
